github_project_number: 42
github_repo: technomaton/edpa-e2e-v181-1778094562
items:
  E-1:
    issue_number: 2
    node_id: I_kwDOSWMrpM8AAAABBeM6bg
    project_item_id: PVTI_lADOAP4s484BW6adzgr-3PQ
  F-1:
    issue_number: 3
    node_id: I_kwDOSWMrpM8AAAABBeM79Q
    project_item_id: PVTI_lADOAP4s484BW6adzgr-3R4
  I-1:
    issue_number: 1
    node_id: I_kwDOSWMrpM8AAAABBeM5Gw
    project_item_id: PVTI_lADOAP4s484BW6adzgr-3OI
  S-1:
    issue_number: 4
    node_id: I_kwDOSWMrpM8AAAABBeM9WQ
    project_item_id: PVTI_lADOAP4s484BW6adzgr-3Tg
